const DEFAULT_CLASSROOM_CONFIG = Object.freeze({
    autoDiscover: true,
    name: "",
    code: "",
    teacherCodeConfigured: false,
});

export function createResourcesState() {
    return {
        resourcesCache: [],
        resourcesMeta: {},
        searchTimer: null,
        initialized: false,
        submitUrl: "",
        repoUrl: "",
        rawBaseUrl: "",
        indexBranch: "main",
        remoteSources: [],
        displayedResources: [],
        filteredResources: [],
        currentResource: null,
        isMockData: false,
        localCourses: [],
        createSource: "local",
        createEntryMode: "new",
        editingCourseId: null,
        createStep: 1,
        scannedCourse: null,
        scanSummary: null,
        scanError: "",
        publishStatus: "idle",
        draftSections: [],
        cloudImported: false,
        cloudCourseOptions: [],
        cloudSourceRows: [],
        cloudSourcesLoaded: false,
        cloudTempSource: null,
        cloudTempToken: "",
        defaultCloudSourceConfigured: false,
        activeSectionIndex: 0,
        activeExperimentIndex: 0,
        activeCourseWorkspaceTab: "route",
        openingStudentLessonTab: false,
        pendingTeacherModeShellSync: false,
        sectionDetailMode: false,
        runningExperimentKey: "",
        remoteSource: "remote",
        classroomConfig: { ...DEFAULT_CLASSROOM_CONFIG },
        classroomState: {
            active: false,
            connected: false,
            searching: false,
            classrooms: [],
            source: null,
            name: "",
            activeCourseId: "",
            activeCourseOriginId: "",
            activeCourseTitle: "",
            activeSectionIndex: null,
            activeSectionTitle: "",
        },
        classroomSyncTimer: null,
        teacherModeReady: false,
        teacherMode: {
            unlocked: false,
            code: "",
        },
        detailMoreMenuBound: false,
        createEntryMenuBound: false,
        resourcesSearchExpanded: false,
        resourcesPageReady: false,
        resourcesPageInitPromise: null,
        resourcesIndexLoadPromise: null,
    };
}
